### PR TITLE
Correct hint in error message to match plugin's ProblemFilter class

### PR DESCRIPTION
**Pull request by lefou**
As this plugin comes with it's own ProblemFilter class which has a
different name, the helpful error message of MiMa can't be copy-and-pasted.
This PR replaces the string to allow copy-and-paste-ing.

### CODE REVIEW

**Comment by lefou** [comment]
Bump

**Comment by lolgab** [comment]
Sorry, hadn't the time to look at it. I'll check it this weekend :)

**Comment by lefou** [comment]
This is a friendly reminder. Also, I wish you Merry Christmas!

**Comment by lolgab** [comment]
Thank you for the reminder. Merry Christmas to you too @lefou :)
I have a review for you too :)
In https://github.com/com-lihaoyi/mill/pull/1638 I refined the algorithm to not add redundant source folders. It made the algorithm more complicated but the number of folders added is very low now :)

**Pull request merged**
